#!/bin/bash
# GENERATED by tb-smith for ${core} — single-hart SCI TB runner.
# Pass criterion: "TB PASS" on stdout.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../.." && pwd)

cd "$REPO"
# The pinned Verilator (5.050; 5.047-devel miscompiles cv32e40x in multi-core
# builds) or a refusal -- never PATH's by default.
source "$REPO/tb/tools.sh"
mosaic_need_verilator
rm -rf "build/tb_${core}_sci_obj"
verilator --binary -j 0 --timescale 1ns/1ps --top-module tb_${core}_sci \
  --Mdir "build/tb_${core}_sci_obj" -o "Vtb_${core}_sci" \
  -Wno-fatal -Wno-WIDTH -Wno-UNUSEDSIGNAL -Wno-UNDRIVEN -Wno-UNUSEDPARAM \
  -Wno-DECLFILENAME -Wno-PINMISSING -Wno-CASEINCOMPLETE -Wno-WIDTHEXPAND \
  -Wno-WIDTHTRUNC -Wno-UNOPTFLAT -Wno-TIMESCALEMOD -Wno-LATCH -Wno-MULTIDRIVEN \
  -Wno-GENUNNAMED -Wno-SYMRSVDWORD -Wno-IMPLICIT -Wno-COMBDLY \
  hw/core-v-mini-mcu/include/obi_pkg.sv \
  tb/mosaic/tb_obi_mem.sv \
  hw/sci/${core}_sci.sv \
  -f "$HERE/deps.f" \
  "$HERE/tb_${core}_sci.sv"

"build/tb_${core}_sci_obj/Vtb_${core}_sci"
