// GENERATED by tb-smith for ${core} — do not edit by hand, regenerate with:
//   python3 -m harness tb-smith generate ${core}
//
// Single-hart SCI-level verification of ${core}_sci against tb_obi_mem
// (which bakes the 4-word demo program at byte 0x180: write sentinel 0x55
// to byte 0x40). Phases: reset -> dormancy -> wake -> liveness -> sentinel.
// Markers parsed by `tb-smith run`: TB PASS / TB FAIL reason=<r>, plus
// instr_reqs= data_reqs= cycles=.

module tb_${core}_sci;

  logic clk = 0;
  logic rst_n = 0;
  always #5 clk = ~clk;

  logic fetch_enable;
  logic core_sleep;

% if unified:
  obi_pkg::obi_req_t  mem_req;
  obi_pkg::obi_resp_t mem_resp;
% else:
  obi_pkg::obi_req_t  instr_req, data_req;
  obi_pkg::obi_resp_t instr_resp, data_resp;
% endif

  ${core}_sci dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .hart_id_i     (32'd1),
      .fetch_enable_i(fetch_enable),
      .core_sleep_o  (core_sleep),
      .irq_i         (32'b0),
      .debug_req_i   (1'b0),
% if unified:
      .mem_req_o     (mem_req),
      .mem_resp_i    (mem_resp)
% else:
      .instr_req_o   (instr_req),
      .instr_resp_i  (instr_resp),
      .data_req_o    (data_req),
      .data_resp_i   (data_resp)
% endif
  );

% if unified:
  tb_obi_mem u_mem (.clk_i(clk), .rst_ni(rst_n), .req_i(mem_req), .resp_o(mem_resp));
% else:
  tb_obi_mem u_imem (.clk_i(clk), .rst_ni(rst_n), .req_i(instr_req), .resp_o(instr_resp));
  tb_obi_mem u_dmem (.clk_i(clk), .rst_ni(rst_n), .req_i(data_req), .resp_o(data_resp));
% endif

  // liveness counters
  int unsigned instr_reqs = 0, data_reqs = 0, cycles = 0;
  always @(posedge clk) begin
    cycles <= cycles + 1;
% if unified:
    if (mem_req.req) data_reqs <= data_reqs + 1;
% else:
    if (instr_req.req) instr_reqs <= instr_reqs + 1;
    if (data_req.req)  data_reqs  <= data_reqs + 1;
% endif
  end

% if unified:
  wire [31:0] sentinel = u_mem.mem['h10];   // byte 0x40
% else:
  wire [31:0] sentinel = u_dmem.mem['h10];  // byte 0x40 (data side)
% endif

  task automatic fail(input string reason);
    $display("TB FAIL reason=%s instr_reqs=%0d data_reqs=%0d cycles=%0d",
             reason, instr_reqs, data_reqs, cycles);
    $fatal(1, "SCI testbench failure");
  endtask

  initial begin
    int unsigned reqs_before;
    bit passed;
    fetch_enable = 1'b0;
    passed = 1'b0;

    // (1) reset
    repeat (20) @(posedge clk);
    // Off the capture edge. Deasserting in the same timestep as posedge clk
    // races async-reset flops against the clock, and the winner is decided by
    // the delta-cycle depth of the reset tree vs the clock tree -- by
    // buffering. See tb/gls/README.md.
    @(negedge clk);
    rst_n = 1'b1;

    // (2) dormancy: parked core must not touch the bus and must report sleep
    repeat (200) @(posedge clk);
    if (instr_reqs + data_reqs != 0) fail("dormancy_bus_activity");
    if (core_sleep !== 1'b1)         fail("dormancy_sleep_flag");

    // (3) wake (level — mirrors the cpu_subsystem latched TDU wake)
    fetch_enable = 1'b1;

    // (4)(5) run to sentinel or watchdog
    repeat (${watchdog}) begin
      @(posedge clk);
      if (sentinel == 32'h0000_0055) begin
        if (instr_reqs + data_reqs == 0) fail("sentinel_without_bus_activity");
        passed = 1'b1;
        break;
      end
    end
    if (passed) begin
      $display("TB PASS instr_reqs=%0d data_reqs=%0d cycles=%0d",
               instr_reqs, data_reqs, cycles);
    end else begin
      if (instr_reqs + data_reqs == 0) fail("liveness_no_requests");
      fail("watchdog_no_sentinel");
    end
    $finish;
  end

endmodule : tb_${core}_sci
