"""The LibreLane configs must stay machine-independent.

They used to carry ~526 absolute paths into a content-addressed FuseSoC build
directory. That made the committed signoff unreproducible anywhere else -- on
another machine every path pointed at a directory that does not exist -- and it
had a worse failure mode than "file not found": a path that still RESOLVED, to
an older bundle, would harden stale RTL and report clean results for the wrong
design.

flow/librelane/scripts/gen_filelist.py now resolves the list at run time. These
tests keep it that way.
"""

from __future__ import annotations

import importlib.util
import pathlib
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
GEN = REPO / "flow" / "librelane" / "scripts" / "gen_filelist.py"
CONFIGS = sorted((REPO / "flow" / "librelane" / "experimental").glob("config_blocka*.yaml"))


def _load():
    spec = importlib.util.spec_from_file_location("ll_gen_filelist", GEN)
    module = importlib.util.module_from_spec(spec)
    sys.modules["ll_gen_filelist"] = module
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize("config", CONFIGS, ids=lambda p: p.name)
def test_configs_carry_no_absolute_paths(config):
    """The anti-regression guard: a hand-pasted path list must not come back."""
    offenders = [
        line.strip()
        for line in config.read_text().splitlines()
        if line.strip().startswith("- /") and not line.strip().startswith("- //")
    ]
    assert not offenders, (
        f"{config.name} contains absolute paths again ({len(offenders)}); "
        "the file list must be generated by scripts/gen_filelist.py"
    )


@pytest.mark.parametrize("config", CONFIGS, ids=lambda p: p.name)
def test_configs_do_not_declare_source_lists(config):
    text = config.read_text()
    for key in ("VERILOG_FILES:", "VERILOG_INCLUDE_DIRS:"):
        assert key not in text, (
            f"{config.name} declares {key}; it is resolved at run time instead"
        )


def test_dma_subsystem_survives_the_dma_ip_exclusion():
    """The exclusion that was almost wrong.

    `soc.dma: none` drops the DMA IP (x-heep_ip_dma_0) but NOT the bus plumbing
    in x-heep_ip_dma_subsystem_0, which the crossbar still instantiates. A
    prefix match drops both and the design loses modules it needs.
    """
    gen = _load()
    base = "/w/build/src/%s/rtl/x.sv"
    assert gen.excluded(base % "x-heep_ip_dma_0")
    assert not gen.excluded(base % "x-heep_ip_dma_subsystem_0")


def test_unsynthesisable_and_example_sources_are_excluded():
    gen = _load()
    base = "/w/build/src/%s/rtl/x.sv"
    for core in ("lowrisc_dv_dpi_uartdpi_0.1",
                 "pulp-platform.org__pulpissimo_remote_bitbang_0",
                 "example_ip_slow_memory_0",
                 "x-heep_ip_pdm2pcm_0",
                 "x-heep_ip_i2s_0"):
        assert gen.excluded(base % core), core


def test_only_tc_clk_is_dropped_from_tech_cells_generic():
    """GF180 has no latch cell, so the generic tc_clk is replaced --
    but the rest of that core (tc_sram, tc_pwr) is still required."""
    gen = _load()
    root = "/w/build/src/pulp-platform.org__tech_cells_generic_0/pulp_platform/tech_cells_generic/src"
    assert gen.excluded(f"{root}/rtl/tc_clk.sv")
    assert not gen.excluded(f"{root}/rtl/tc_sram.sv")
    assert not gen.excluded(f"{root}/tc_pwr.sv")


def test_extra_sources_exist():
    """The ASIC-side files are not in the FuseSoC graph, so a rename would
    otherwise be found only by a failing hours-long flow."""
    gen = _load()
    for rel in gen.EXTRA_SOURCES:
        assert (REPO / rel).is_file(), rel
