#!/usr/bin/env python3
"""Generate gls_powerup_init.svh -- a power-up state for Icarus gate-level runs.

4 081 of this design's 5 587 flip-flops are plain dffq_1 with no reset. At time
zero in a gate-level simulation they are X, and X-propagation stops the netlist
booting: the first attempt sat at 126 000 cycles with the QSPI pins stuck at x.

Real silicon powers up to a definite 0 or 1, never X, so depositing a defined
value models the part rather than flattering it -- the deposit only holds until
each flop's first clock edge, after which normal logic takes over. Verilator
hides the whole issue by zero-initialising, which is why no RTL run ever showed
it.

CVC does not need this file: +random_2state=<seed> initialises all state to
random 0/1, which is a stronger model because a different seed is a different
power-up state. See run_gls_cvc.sh.

Usage:  ./gen_powerup_init.py [netlist.v] [output.svh]
"""
from __future__ import annotations

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]

DEFAULT_NETLIST = (
    REPO
    / "flow/librelane/experimental/runs/blocka_signoff/final/pnl/mosaic_block_a.pnl.v"
)
DEFAULT_OUTPUT = HERE / "gls_powerup_init.svh"

# Every sequential cell the design instantiates. Physical-only cells (fill, tap,
# endcap, antenna) hold no state and are deliberately absent.
FLOP_CELLS = ("dffq_1", "dffrnq_1", "dffsnq_1", "dffnq_1")

HEADER = """// GENERATED by tb/gls/gen_powerup_init.py -- do not edit.
//
// Power-up state for gate-level simulation. {n} flip-flops are deposited to a
// defined value at time 0 so X-propagation from unreset flops cannot stall the
// netlist. See the generator for why this models silicon rather than hiding a
// problem.
//
// Netlist: {netlist}

initial begin
"""


def q_nets(netlist: pathlib.Path) -> list[str]:
    text = netlist.read_text(errors="replace")
    pattern = re.compile(
        r"gf180mcu_fd_sc_mcu7t5v0__(?:%s)\s+\S+\s*\((.*?)\);" % "|".join(FLOP_CELLS),
        re.S,
    )
    nets: list[str] = []
    seen: set[str] = set()
    for match in pattern.finditer(text):
        q = re.search(r"\.Q\(\s*(\\?.*?)\s*\)\s*[,)]", match.group(1), re.S)
        if not q:
            continue
        net = q.group(1).strip()
        if not net or net in seen or net.startswith("1'b"):
            continue
        seen.add(net)
        nets.append(net)
    return nets


def main() -> int:
    netlist = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_NETLIST
    output = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUTPUT
    # The macro is not always the testbench's direct child. With a padframe
    # model in between it sits at gls_tb.dut.dut, and every one of these
    # thousands of hierarchical references has to name the real scope or
    # iverilog reports one bind failure per flop.
    scope = sys.argv[3] if len(sys.argv) > 3 else "gls_tb.dut"
    if not netlist.is_file():
        print(f"netlist not found: {netlist}", file=sys.stderr)
        return 2

    nets = q_nets(netlist)
    if not nets:
        print("no flop Q nets found -- has the netlist format changed?", file=sys.stderr)
        return 1

    lines = [HEADER.format(n=len(nets), netlist=netlist.name)]
    for net in nets:
        # Escaped identifiers keep their trailing space inside the hierarchical
        # reference; plain ones must not gain one.
        ref = f"{scope}.{net} " if net.startswith("\\") else f"{scope}.{net}"
        lines.append(f"  $deposit({ref}, 1'b0);")
    lines.append("end")
    output.write_text("\n".join(lines) + "\n")
    print(f"wrote {output} ({len(nets)} deposits)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
