#!/usr/bin/env python3
"""Generate gf180mcu_cells_cvc.v -- a standards-compliant copy of the GF180
standard-cell Verilog models, for timing-annotated gate-level simulation.

THE PROBLEM
-----------
The PDK models use `ifnone` on EDGE-SENSITIVE specify paths:

    ifnone
     (posedge A1 => (ZN:A1)) = (1.0,1.0);

IEEE 1364-2005 section 14.2.6 forbids this -- `ifnone` supplies the default for
STATE-dependent simple paths only, and explicitly not for edge-sensitive ones.
Two independent simulators reject it, both correctly:

    iverilog: sorry: ifnone with an edge-sensitive path is not supported
    CVC:      ERROR [1043]/[1012] ifnone path illegal - has edge or is state dependent

That is why no open-source simulator will do SDF-annotated GLS on GF180 without
patching the models: under Icarus they must be compiled -DFUNCTIONAL, which
drops the specify blocks entirely -- and with them the very paths SDF annotates.

WHAT THIS DOES
--------------
Removes the `ifnone` KEYWORD from edge-sensitive paths and leaves the path
itself. The path therefore survives as an SDF annotation target and receives its
real delay, rather than being deleted (which would silently give those arcs zero
delay). The cost is semantic: such a path becomes unconditional instead of
"apply only when no other condition matched".

State-dependent `ifnone` blocks -- the legal ones -- are left untouched.

Nothing in the PDK is modified; this writes a separate copy under tb/gls/.

Usage:  ./mk_cells_cvc.py [source.v] [output.v]
"""
from __future__ import annotations

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]

DEFAULT_SRC = (
    REPO
    / "flow/librelane/gf180mcu/gf180mcuD/libs.ref/gf180mcu_fd_sc_mcu7t5v0"
    / "verilog/gf180mcu_fd_sc_mcu7t5v0.v"
)
DEFAULT_OUT = HERE / "gf180mcu_cells_cvc.v"

EDGE = re.compile(r"\b(posedge|negedge)\b")

HEADER = """// GENERATED by tb/gls/mk_cells_cvc.py -- do not edit.
//
// Standards-compliant copy of the GF180MCU standard-cell models. The PDK models
// use `ifnone` on edge-sensitive specify paths, which IEEE 1364-2005 section
// 14.2.6 forbids and which both iverilog and CVC reject. This copy removes the
// illegal `ifnone` keyword and keeps the path, so it stays an SDF annotation
// target instead of losing its delay.
//
// {n} illegal ifnone keywords removed; {kept} legal state-dependent ifnone
// blocks left untouched. Source: {src}
//
"""


def patch(lines: list[str]) -> tuple[list[str], int]:
    out: list[str] = []
    removed = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip() == "ifnone":
            # Look ahead past comments/blanks to the path statement it qualifies.
            j = i + 1
            while j < len(lines) and (
                lines[j].strip().startswith("//") or not lines[j].strip()
            ):
                j += 1
            if j < len(lines) and EDGE.search(lines[j]):
                removed += 1
                i += 1  # drop the ifnone keyword, keep the path
                continue
        out.append(line)
        i += 1
    return out, removed


def main() -> int:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    out_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    if not src.is_file():
        print(f"source models not found: {src}", file=sys.stderr)
        return 2

    lines = src.read_text(errors="replace").split("\n")
    patched, removed = patch(lines)
    kept = sum(1 for line in patched if line.strip() == "ifnone")
    if removed == 0:
        print("no edge-sensitive ifnone found -- has the PDK been fixed upstream?")
    out_path.write_text(HEADER.format(n=removed, kept=kept, src=src.name) + "\n".join(patched))
    print(f"wrote {out_path} ({removed} removed, {kept} legal ifnone kept)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
