#!/usr/bin/env python3
"""Generate spiflash_v2001.v -- a Verilog-2001 copy of x-heep's QSPI flash model.

CVC is an IEEE 1364-2005 simulator, not a SystemVerilog one: it rejects `logic`.
The upstream model (x-heep__tb-utils yosys_spiflash.sv) uses `logic` for 23
plain internal signals and nothing else from SystemVerilog -- no always_ff, no
typedefs, structs or enums -- so a mechanical `logic` -> `reg` conversion plus an
explicit memory range is behaviour-preserving.

This exists only because timing-annotated GLS needs CVC. The Icarus flow uses
the upstream model directly.

Usage:  ./mk_spiflash_v2001.py [source.sv] [output.v]
"""
from __future__ import annotations

import glob
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
DEFAULT_OUT = HERE / "spiflash_v2001.v"

HEADER = """// GENERATED by tb/gls/mk_spiflash_v2001.py -- do not edit.
//
// Verilog-2001 copy of x-heep's yosys_spiflash.sv, for CVC, which rejects
// `logic`. A mechanical `logic` -> `reg` conversion plus an explicit memory
// range; behaviour is unchanged. Source: {src}
//
"""


def newest_upstream() -> pathlib.Path | None:
    pattern = str(
        REPO
        / "build/mosaic/mosaic_tapeout_ultra-*/runs/fusesoc.*"
        / "build/src/x-heep__tb-utils_0/yosys_spiflash.sv"
    )
    found = glob.glob(pattern)
    if not found:
        return None
    return pathlib.Path(max(found, key=lambda p: pathlib.Path(p).stat().st_mtime))


def main() -> int:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else newest_upstream()
    out_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    if src is None or not src.is_file():
        print(
            "upstream yosys_spiflash.sv not found -- run a FuseSoC setup first,"
            " or pass the path explicitly",
            file=sys.stderr,
        )
        return 2

    text = src.read_text(errors="replace")
    text = re.sub(r"^(\s*)logic(\s)", r"\1reg\2", text, flags=re.M)
    text = text.replace(
        "reg [7:0] memory[16*1024*1024];", "reg [7:0] memory[0:16*1024*1024-1];"
    )
    leftover = len(re.findall(r"^\s*logic\s", text, flags=re.M))
    if leftover:
        print(f"WARNING: {leftover} `logic` declarations left unconverted", file=sys.stderr)
    out_path.write_text(HEADER.format(src=src.name) + text)
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
