// Copyright MOSAIC-SoC
// SPDX-License-Identifier: Apache-2.0
#ifndef MOSAIC_SW_DEVICE_LIB_DRIVERS_IDMA_IDMA_REGS_H_
#define MOSAIC_SW_DEVICE_LIB_DRIVERS_IDMA_IDMA_REGS_H_

// One complete idma_reg32_3d block occupies 0x114 bytes. MOSAIC rounds each
// stream's private descriptor bank up to 0x200 bytes.
#define IDMA_STREAM_STRIDE 0x200u

#define IDMA_CONF_REG_OFFSET 0x000u
#define IDMA_STATUS_BASE_REG_OFFSET 0x004u
#define IDMA_NEXT_ID_BASE_REG_OFFSET 0x044u
#define IDMA_DONE_ID_BASE_REG_OFFSET 0x084u
#define IDMA_DST_ADDR_REG_OFFSET 0x0d0u
#define IDMA_SRC_ADDR_REG_OFFSET 0x0d8u
#define IDMA_LENGTH_REG_OFFSET 0x0e0u
#define IDMA_DST_STRIDE_2_REG_OFFSET 0x0e8u
#define IDMA_SRC_STRIDE_2_REG_OFFSET 0x0f0u
#define IDMA_REPS_2_REG_OFFSET 0x0f8u
#define IDMA_DST_STRIDE_3_REG_OFFSET 0x100u
#define IDMA_SRC_STRIDE_3_REG_OFFSET 0x108u
#define IDMA_REPS_3_REG_OFFSET 0x110u

// MOSAIC wrapper extension: atomic cooperative stream ownership.
#define IDMA_OWNER_CLAIM_REG_OFFSET 0x180u
#define IDMA_OWNER_RELEASE_REG_OFFSET 0x184u
#define IDMA_OWNER_REG_OFFSET 0x188u

#define IDMA_CONF_ENABLE_ND_OFFSET 10u
#define IDMA_CONF_SRC_PROTOCOL_OFFSET 12u
#define IDMA_CONF_DST_PROTOCOL_OFFSET 15u
#define IDMA_PROTOCOL_OBI 1u
#define IDMA_STATUS_BUSY_MASK 0x3ffu

#endif  // MOSAIC_SW_DEVICE_LIB_DRIVERS_IDMA_IDMA_REGS_H_
