// GENERATED by tb-smith for hazard3 — do not edit by hand, regenerate with:
//   python3 -m harness tb-smith generate hazard3
//
// Single-hart SCI-level verification of hazard3_sci against tb_obi_mem
// (which bakes the 4-word demo program at byte 0x180: write sentinel 0x55
// to byte 0x40). Phases: reset -> dormancy -> wake -> liveness -> sentinel.
// Markers parsed by `tb-smith run`: TB PASS / TB FAIL reason=<r>, plus
// instr_reqs= data_reqs= cycles=.

module tb_hazard3_sci;

  logic clk = 0;
  logic rst_n = 0;
  always #5 clk = ~clk;

  logic fetch_enable;
  logic core_sleep;

  obi_pkg::obi_req_t instr_req, data_req;
  obi_pkg::obi_resp_t instr_resp, data_resp;

  hazard3_sci dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .hart_id_i     (32'd1),
      .fetch_enable_i(fetch_enable),
      .core_sleep_o  (core_sleep),
      .irq_i         (32'b0),
      .debug_req_i   (1'b0),
      .instr_req_o   (instr_req),
      .instr_resp_i  (instr_resp),
      .data_req_o    (data_req),
      .data_resp_i   (data_resp)
  );

  tb_obi_mem u_imem (
      .clk_i (clk),
      .rst_ni(rst_n),
      .req_i (instr_req),
      .resp_o(instr_resp)
  );
  tb_obi_mem u_dmem (
      .clk_i (clk),
      .rst_ni(rst_n),
      .req_i (data_req),
      .resp_o(data_resp)
  );

  // liveness counters
  int unsigned instr_reqs = 0, data_reqs = 0, cycles = 0;
  always @(posedge clk) begin
    cycles <= cycles + 1;
    if (instr_req.req) instr_reqs <= instr_reqs + 1;
    if (data_req.req) data_reqs <= data_reqs + 1;
  end

  wire [31:0] sentinel = u_dmem.mem['h10];  // byte 0x40 (data side)

  task automatic fail(input string reason);
    $display("TB FAIL reason=%s instr_reqs=%0d data_reqs=%0d cycles=%0d", reason, instr_reqs,
             data_reqs, cycles);
    $fatal(1, "Hazard3 SCI test failed: %s", reason);
  endtask

  initial begin
    int unsigned reqs_before;
    bit passed;
    fetch_enable = 1'b0;
    passed = 1'b0;

    // (1) reset
    repeat (20) @(posedge clk);
    // Off the capture edge: deasserting in the same timestep as posedge
    // clk races the async-reset flops against the clock. See tb/gls/README.md.
    @(negedge clk);
    rst_n = 1'b1;

    // (2) dormancy: parked core must not touch the bus and must report sleep
    repeat (200) @(posedge clk);
    if (instr_reqs + data_reqs != 0) fail("dormancy_bus_activity");
    if (core_sleep !== 1'b1) fail("dormancy_sleep_flag");

    // (3) wake (level — mirrors the cpu_subsystem latched TDU wake)
    fetch_enable = 1'b1;

    // (4)(5) run to sentinel or watchdog
    repeat (200000) begin
      @(posedge clk);
      if (sentinel == 32'h0000_0055) begin
        if (instr_reqs + data_reqs == 0) fail("sentinel_without_bus_activity");
        passed = 1'b1;
        break;
      end
    end
    if (passed) begin
      $display("TB PASS instr_reqs=%0d data_reqs=%0d cycles=%0d", instr_reqs, data_reqs, cycles);
    end else begin
      if (instr_reqs + data_reqs == 0) fail("liveness_no_requests");
      fail("watchdog_no_sentinel");
    end
    $finish;
  end

endmodule : tb_hazard3_sci
