// Copyright 2026 MOSAIC-SoC contributors.
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// ${core}_sci.sv — Standard Core Interface wrapper for ${core} (AHB-Lite).
//
// GENERATED by wrapper-smith (family ahb_split) from ${analysis_name}.
// The AHB-Lite -> OBI conversion below is complete for single transfers and
// treats burst beats (SEQ) as independent accesses — legal because this
// subordinate controls HREADY. Fill every TODO(wrapper-smith) marker, then
// verify with: python3 -m harness tb-smith generate ${core} && tb-smith run ${core}.
//
// Conversion contract (per port, single outstanding):
//   address phase : HTRANS[1] (NONSEQ/SEQ) accepted when our HREADY is high
//   data phase    : HREADY held LOW while the OBI transaction is in flight;
//                   HWDATA is stable for the whole stalled data phase, so it
//                   feeds OBI wdata directly (no capture register needed)
//   completion    : OBI rvalid -> one HREADY-high cycle with HRDATA = rdata;
//                   that same cycle carries the master's next address phase
//   byte enables  : HSIZE + HADDR[1:0] -> OBI be (writes; reads use 4'hF)
//   HRESP         : tied OKAY (OBI has no error channel — same policy as the
//                   AXI/TileLink bridges)

module ${core}_sci #(
    parameter logic [31:0] BOOT_ADDR = 32'h00000180
) (
    input logic clk_i,
    input logic rst_ni,

    // Core control
    input  logic [31:0] hart_id_i,
    input  logic        fetch_enable_i,
    output logic        core_sleep_o,

    // Interrupts (RISC-V mip bit layout: 3=MSIP, 7=MTIP, 11=MEIP)
    input  logic [31:0] irq_i,

    // Debug
    input  logic        debug_req_i,  // TODO(wrapper-smith): wire if the core has a debug req input

    // OBI split master ports
    output obi_pkg::obi_req_t  instr_req_o,
    input  obi_pkg::obi_resp_t instr_resp_i,
    output obi_pkg::obi_req_t  data_req_o,
    input  obi_pkg::obi_resp_t data_resp_i
);

    // Reset-hold dormancy: the core is held in reset until the TDU wake
    // (fetch_enable_i) — identical policy to every other SCI wrapper.
    logic core_rst_n;
    assign core_rst_n = rst_ni & fetch_enable_i;

    // ── AHB wires (I-port and D-port) ────────────────────────────────
    logic [31:0] i_haddr, d_haddr;
    logic        i_hwrite, d_hwrite;
    logic [2:0]  i_hsize, d_hsize;
    logic [1:0]  i_htrans, d_htrans;
    logic [31:0] i_hwdata, d_hwdata;
    logic [31:0] i_hrdata, d_hrdata;
    logic        i_hready, d_hready;
    logic        i_hresp, d_hresp;

    // ── the core ─────────────────────────────────────────────────────
    // TODO(wrapper-smith): verify instance ports against the analysis port
    // list (${top}); tie off ports not listed here (hburst/hprot/hmastlock/
    // hexcl/dbg_* -> '0; hexokay-style inputs -> 1'b0 or per spec).
    ${top} #(
        // TODO(wrapper-smith): map the reset-vector parameter (analysis
        // 'control.boot'). Hazard3: RESET_VECTOR + MTVEC_INIT.
        .RESET_VECTOR(BOOT_ADDR)
    ) i_core (
        .clk         (clk_i),
        .rst_n       (core_rst_n),
        // I-port AHB
        .i_haddr     (i_haddr),
        .i_hwrite    (i_hwrite),
        .i_hsize     (i_hsize),
        .i_htrans    (i_htrans),
        .i_hwdata    (i_hwdata),
        .i_hrdata    (i_hrdata),
        .i_hready    (i_hready),
        .i_hresp     (i_hresp),
        // D-port AHB
        .d_haddr     (d_haddr),
        .d_hwrite    (d_hwrite),
        .d_hsize     (d_hsize),
        .d_htrans    (d_htrans),
        .d_hwdata    (d_hwdata),
        .d_hrdata    (d_hrdata),
        .d_hready    (d_hready),
        .d_hresp     (d_hresp)
        // TODO(wrapper-smith): irq mapping — SCI contract: irq_i[3]=msip,
        // irq_i[7]=mtip, irq_i[11]=meip (e.g. .soft_irq(irq_i[3]),
        // .timer_irq(irq_i[7]), .irq({...irq_i[11]...})).
    );

    // ── AHB-Lite -> OBI, one converter per port ──────────────────────
    // state: 0 = address phase idle (HREADY high), 1 = OBI in flight
    //        (HREADY low until rvalid)

    function automatic logic [3:0] ahb_be(input logic [2:0] size,
                                          input logic [1:0] a);
        unique case (size[1:0])
            2'b00:   return 4'b0001 << a;                 // byte
            2'b01:   return a[1] ? 4'b1100 : 4'b0011;     // half
            default: return 4'b1111;                      // word
        endcase
    endfunction

    // ---- instruction port ----
    logic        i_busy_q, i_granted_q;
    logic [31:0] i_addr_q;
    logic        i_write_q;
    logic [2:0]  i_size_q;

    assign i_hready = ~i_busy_q | instr_resp_i.rvalid;
    assign i_hresp  = 1'b0;
    assign i_hrdata = instr_resp_i.rdata;

    assign instr_req_o.req   = i_busy_q & ~i_granted_q & fetch_enable_i;
    assign instr_req_o.addr  = {i_addr_q[31:2], 2'b00};
    assign instr_req_o.we    = i_write_q;
    assign instr_req_o.be    = i_write_q ? ahb_be(i_size_q, i_addr_q[1:0]) : 4'hF;
    assign instr_req_o.wdata = i_hwdata;  // stable during the stalled data phase

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            i_busy_q    <= 1'b0;
            i_granted_q <= 1'b0;
            i_addr_q    <= '0;
            i_write_q   <= 1'b0;
            i_size_q    <= '0;
        end else begin
            if (instr_req_o.req && instr_resp_i.gnt) i_granted_q <= 1'b1;
            if (instr_resp_i.rvalid) begin
                i_busy_q    <= 1'b0;
                i_granted_q <= 1'b0;
            end
            // accept an address phase whenever HREADY is high
            if (i_hready && i_htrans[1] && core_rst_n) begin
                i_busy_q  <= 1'b1;
                i_addr_q  <= i_haddr;
                i_write_q <= i_hwrite;
                i_size_q  <= i_hsize;
            end
        end
    end

    // ---- data port ----
    logic        d_busy_q, d_granted_q;
    logic [31:0] d_addr_q;
    logic        d_write_q;
    logic [2:0]  d_size_q;

    assign d_hready = ~d_busy_q | data_resp_i.rvalid;
    assign d_hresp  = 1'b0;
    assign d_hrdata = data_resp_i.rdata;

    assign data_req_o.req   = d_busy_q & ~d_granted_q & fetch_enable_i;
    assign data_req_o.addr  = {d_addr_q[31:2], 2'b00};
    assign data_req_o.we    = d_write_q;
    assign data_req_o.be    = d_write_q ? ahb_be(d_size_q, d_addr_q[1:0]) : 4'hF;
    assign data_req_o.wdata = d_hwdata;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            d_busy_q    <= 1'b0;
            d_granted_q <= 1'b0;
            d_addr_q    <= '0;
            d_write_q   <= 1'b0;
            d_size_q    <= '0;
        end else begin
            if (data_req_o.req && data_resp_i.gnt) d_granted_q <= 1'b1;
            if (data_resp_i.rvalid) begin
                d_busy_q    <= 1'b0;
                d_granted_q <= 1'b0;
            end
            if (d_hready && d_htrans[1] && core_rst_n) begin
                d_busy_q  <= 1'b1;
                d_addr_q  <= d_haddr;
                d_write_q <= d_hwrite;
                d_size_q  <= d_hsize;
            end
        end
    end

    // No exported sleep state: report "asleep" while parked so the TDU's
    // CORE_STATUS reflects un-woken workers.
    assign core_sleep_o = ~fetch_enable_i;

endmodule : ${core}_sci
